name: Daily Selenium Script

on:
  schedule:
    - cron: '00 16 * * 0-6'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    
  
    - name: Install dependencies
      run: |
        pip install selenium pandas webdriver-manager jupyter nbconvert geocoder
        
    - name: Run  script
      run: jupyter nbconvert --execute --inplace Dengue/NEAwebsite.ipynb
    
    - name: Commit and push changes
      run: |
        git config user.name "AryaVatsa"
        git config user.email "arya.vatsa@icloud.com"
        git add Dengue/NeaDataOverview 
        git add Dengue/NeaLocalityData
        git add Dengue/NeaDataLocalities
        git add Dengue/camps.csv
        git add Dengue/campsNearClusters
        git add Dengue/manualChecks
        git commit -m "Update NeaDataOverview and NeaDataLocalities"
        git push
    

