name: Daily Selenium Script

on:
  schedule:
    - cron: '37 09 * * 0-6'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 2.59
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    
  
    - name: Install dependencies
      run: |
        pip install selenium pandas webdriver-manager jupyter nbconvert
        
    - name: Run  script
      run: python Dengue/NEAwebsite.py
    
    - name: Commit and push changes
      run: |
        git config user.name "AryaVatsa"
        git config user.email "arya.vatsa@icloud.com"
        git add NeaData
        git commit -m "Update NeaData"
        git push
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/AryaVatsa/Daily-Dengue-Cluster-Data-.git
    

