name: Daily Selenium Script

on:
  schedule:
    - cron: '02 06 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    
  
    - name: Install dependencies
      run: |
        pip install selenium pandas webdriver-manager jupyter nbconvert
        
    - name: Run the notebook
      run: jupyter nbconvert --to notebook --execute --debug NEAwebsite.ipynb

