name: Daily Selenium Script

on:
  schedule:
    - cron: '25 05 * * *'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 'pypy3.9'

    - name: Setup Chrome Driver
      uses: nanasess/setup-chromedriver@master
    
    - name: Run Chrome in headless mode
      run: |
          google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 &
  
    - name: Install dependencies
      run: |
        pip install selenium pandas webdriver-manager jupyter nbconvert
        
    - name: Run the notebook
      run: jupyter nbconvert --to notebook --execute -- debug NEAwebsite.ipynb

